# Generated by Django 4.2.3 on 2023-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_accesspoints_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=30)),
                ('ipAddress', models.GenericIPAddressField(unique=True)),
                ('marca', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
