# Generated by Django 4.2.3 on 2023-09-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_switches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=30)),
                ('ipAddress', models.GenericIPAddressField(unique=True)),
                ('service', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
